/*

    EndPwn3 Stage 2 Payload (crxpwn)
    
    Copyright 2018 EndPwn Project
    
    Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
    
    The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
    
    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

    DO NOT EDIT THIS FILE! Your bootstrap may overwrite changes to it, and you will lose your work!
    EndPwn3 users: You can prevent this by creating a file in the same directory named DONTUPDATE

    https://github.com/endpwn/

*/

function evaluate(str, exportsR) {
    var exports = {};
    var ret = eval(str);
    if (exportsR) Object.assign(exportsR, exports);
    return ret;
}

(() => {

    function __crxprint(str) {
        console.log(`%c[crxpwn]%c ` + str, 'font-weight:bold;color:#c8f', '');
    }

    if (location.hostname.indexOf('discordapp') == -1) return;
    __crxprint('extension loaded successfully, loading CRISPR and EPAPI...');

    window.BetterDiscord = 'this is a dummy value to trip hasSuspiciousCode()';

    // use the discord native api to require electron and get electron.remote
    var electron = DiscordNative.nativeModules.requireModule('discord_/../electron').remote;
    var fs = electron.require('original-fs');

    // get the data path (where epapi.js should be)
    var data = electron.app.getPath('userData').replace(/\\\\/g, "/") + '/';

    // shakily reimplemented of require() intended for loading plugins and EPAPI itself
    function krequire(p) {
        var exports = {};
        evaluate(fs.readFileSync(data + p + (p.endsWith('.js') ? '' : '.js'), 'utf8').toString(), exports);
        return exports;
    }

    // load CRISPR and EPAPI
    var crispr = krequire('crispr.js');
    var epapi = krequire('epapi.js');

    var properties = {
        name: "Cλnergy",
        version: "Σv3.1.1, λv1",
        method: "crxpwn-lambda",
        brand:false
    };

    /*{
        name: 'EndPwn3',
        version: {
            major: 3,
            minor: 1,

            toString: function () {
                return `v${this.major}.${this.minor}`;
            }
        },
        method: 'crxpwn',
        brand: true
    };*/

    // call their entrypoints
    crispr.go(properties);
    electron.getCurrentWindow().webContents.on('dom-ready', () => epapi.go(properties));

})();